spring.application.name=jobportal
spring.datasource.username=jobportal
spring.datasource.password=jobportal
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal
<<<<<<< HEAD
=======

logging.level.org.hibernate.sql=debug



>>>>>>> bigbranch
